import tkinter as tk
from tkinter import ttk
import src.view.ShowFile as ShowFile

class AlgorithmTestingFrame:
    def __init__(self, mainwin, title, dir_location):
        self.mainWin = mainwin
        self.AlgorithmTestingFrame = tk.Toplevel(mainwin)
        self.AlgorithmTestingFrame.title(title)
        self.finalAnalysisReport_button = ttk.Button(self.AlgorithmTestingFrame, text="Reporte Final")
        self.finalAnalysisReport_button.grid(row=0, column=0, padx=10, pady=10, sticky="ew")
        self.finalAnalysisReport_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/finalAnalysisReport.txt"))
        self.freq_button = ttk.Button(self.AlgorithmTestingFrame, text="Frecuencias")
        self.freq_button.grid(row=0, column=1, padx=10, pady=10, sticky="ew")
        self.freq_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/freq.txt"))
        self.resT1_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 1")
        self.resT1_button.grid(row=0, column=2, padx=10, pady=10, sticky="ew")
        self.resT1_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/Frequency/results.txt"))
        self.stats_T1_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 1")
        self.stats_T1_button.grid(row=0, column=3, padx=10, pady=10, sticky="ew")
        self.stats_T1_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/Frequency/stats.txt"))
        self.resT2_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 2")
        self.resT2_button.grid(row=1, column=0, padx=10, pady=10, sticky="ew")
        self.resT2_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/BlockFrequency/results.txt"))
        self.stats_T2_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 2")
        self.stats_T2_button.grid(row=1, column=1, padx=10, pady=10, sticky="ew")
        self.stats_T2_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/BlockFrequency/stats.txt"))
        self.resT3_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 3")
        self.resT3_button.grid(row=1, column=2, padx=10, pady=10, sticky="ew")
        self.resT3_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/Runs/results.txt"))
        self.stats_T3_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 3")
        self.stats_T3_button.grid(row=1, column=3, padx=10, pady=10, sticky="ew")
        self.stats_T3_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/Runs/stats.txt"))
        self.resT4_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 4")
        self.resT4_button.grid(row=2, column=0, padx=10, pady=10, sticky="ew")
        self.resT4_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/LongestRunOfOnes/results.txt"))
        self.stats_T4_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 4")
        self.stats_T4_button.grid(row=2, column=1, padx=10, pady=10, sticky="ew")
        self.stats_T4_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/LongestRunOfOnes/stats.txt"))
        self.resT5_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 5")
        self.resT5_button.grid(row=2, column=2, padx=10, pady=10, sticky="ew")
        self.resT5_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/Rank/results.txt"))
        self.stats_T5_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 5")
        self.stats_T5_button.grid(row=2, column=3, padx=10, pady=10, sticky="ew")
        self.stats_T5_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/Rank/stats.txt"))
        self.resT6_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 6")
        self.resT6_button.grid(row=3, column=0, padx=10, pady=10, sticky="ew")
        self.resT6_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/DiscreteFourierTransform/results.txt"))
        self.stats_T6_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 6")
        self.stats_T6_button.grid(row=3, column=1, padx=10, pady=10, sticky="ew")
        self.stats_T6_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/DiscreteFourierTransform/stats.txt"))
        self.resT7_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 7")
        self.resT7_button.grid(row=3, column=2, padx=10, pady=10, sticky="ew")
        self.resT7_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/NonOverlappingTemplateMatchings/results.txt"))
        self.stats_T7_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 7")
        self.stats_T7_button.grid(row=3, column=3, padx=10, pady=10, sticky="ew")
        self.stats_T7_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/NonOverlappingTemplateMatchings/stats.txt"))
        self.resT8_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 8")
        self.resT8_button.grid(row=4, column=0, padx=10, pady=10, sticky="ew")
        self.resT8_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/OverlappingTemplateMatchings/results.txt"))
        self.stats_T8_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 8")
        self.stats_T8_button.grid(row=4, column=1, padx=10, pady=10, sticky="ew")
        self.stats_T8_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/OverlappingTemplateMatchings/stats.txt"))
        self.resT9_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 9")
        self.resT9_button.grid(row=4, column=2, padx=10, pady=10, sticky="ew")
        self.resT9_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/Universal/results.txt"))
        self.stats_T9_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 9")
        self.stats_T9_button.grid(row=4, column=3, padx=10, pady=10, sticky="ew")
        self.stats_T9_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/Universal/stats.txt"))
        self.resT10_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 10")
        self.resT10_button.grid(row=5, column=0, padx=10, pady=10, sticky="ew")
        self.resT10_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/LinearComplexity/results.txt"))
        self.stats_T10_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 10")
        self.stats_T10_button.grid(row=5, column=1, padx=10, pady=10, sticky="ew")
        self.stats_T10_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/LinearComplexity/stats.txt"))
        self.resT11_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 11")
        self.resT11_button.grid(row=5, column=2, padx=10, pady=10, sticky="ew")
        self.resT11_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/SerialTest/results.txt"))
        self.stats_T11_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 11")
        self.stats_T11_button.grid(row=5, column=3, padx=10, pady=10, sticky="ew")
        self.stats_T11_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/SerialTest/stats.txt"))
        self.resT12_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 12")
        self.resT12_button.grid(row=6, column=0, padx=10, pady=10, sticky="ew")
        self.resT12_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/ApproximateEntropy/results.txt"))
        self.stats_T12_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 12")
        self.stats_T12_button.grid(row=6, column=1, padx=10, pady=10, sticky="ew")
        self.stats_T12_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/ApproximateEntropy/stats.txt"))
        self.resT13_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 13")
        self.resT13_button.grid(row=6, column=2, padx=10, pady=10, sticky="ew")
        self.resT13_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/CumulativeSums/results.txt"))
        self.stats_T13_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 13")
        self.stats_T13_button.grid(row=6, column=3, padx=10, pady=10, sticky="ew")
        self.stats_T13_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/CumulativeSums/stats.txt"))
        self.resT14_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 14")
        self.resT14_button.grid(row=7, column=0, padx=10, pady=10, sticky="ew")
        self.resT14_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/RandomExcursions/results.txt"))
        self.stats_T14_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 14")
        self.stats_T14_button.grid(row=7, column=1, padx=10, pady=10, sticky="ew")
        self.stats_T14_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/RandomExcursions/stats.txt"))
        self.resT15_button = ttk.Button(self.AlgorithmTestingFrame, text="Resultados Test 15")
        self.resT15_button.grid(row=7, column=2, padx=10, pady=10, sticky="ew")
        self.resT15_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/RandomExcursionsVariant/results.txt"))
        self.stats_T15_button = ttk.Button(self.AlgorithmTestingFrame, text="Estadísticas Test 15")
        self.stats_T15_button.grid(row=7, column=3, padx=10, pady=10, sticky="ew")
        self.stats_T15_button.bind("<Button-1>", lambda event: self.show_file(dir_location + "/RandomExcursionsVariant/stats.txt"))

    def show_file(self, dir_location):
        title = dir_location
        show_file = ShowFile.ShowFile(self.mainWin, title, dir_location)